### ISSUE TITLE
don't save to cache if nothing was changed

### ISSUE THREAD

**Issue by syphar** [syphar/restore-pip-download-cache#7]
the [standard `actions/cache` action will not save the cache at all if we had an exact match when restoring the cache](https://github.com/actions/cache/blob/0781355a23dac32fd3bac414512f4b903437991a/src/save.ts#L32-L37). 

That is the reason why in the [python simple example](https://github.com/actions/cache/blob/main/examples.md#simple-example) looks like: 
```yaml 
- uses: actions/cache@v2
  with:
    path: ~/.cache/pip
    key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
    restore-keys: |
      ${{ runner.os }}-pip-
```

so: 

1. if we want this action to stay a one-liner, then we have to leave the `requirements` out of the cache-key, which means we always have to save the cache 
2. if we want execution to be faster, this action needs (optionally?) the filename pattern for `hashFiles` to include to the cache-key, while providing `restore-keys` on its own. 

## other implementations 
- [gha-npm-cache](https://github.com/c-hive/gha-npm-cache) solves this by hardcoding `package-lock.json` to include. which works for the JS package managers, but breaks for python (pip/poetry/pipenv)
